name: Deploy to Firebase on push to main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        
      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Upload production build
        uses: actions/upload-artifact@v3
        with:
          name: release
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Target project directory
        uses: actions/checkout@v4

      - name: Download production build
        uses: actions/download-artifact@v3
        with:
          name: release
          path: dist

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_DEDEEN_INTERNAL }}'
          projectId: lvdev-fbase
          channelId: live