name: Deploy to Firebase on push to main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Cache npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: |
          for i in 1 2 3; do
            echo "Attempt $i: npm install"
            if npm install; then
              echo "npm install succeeded"
              break
            fi
            echo "npm install failed, retrying in 10 seconds..."
            sleep 10
          done

      - name: Build the project
        run: npm run build -- --mode=dev

      - name: Upload production build
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Target project directory
        uses: actions/checkout@v4

      - name: Download production build
        uses: actions/download-artifact@v4
        with:
          name: release
          path: dist

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_DEDEEN_INTERNAL }}"
          projectId: lvdev-fbase
          channelId: live
